#!/bin/bash
set -e

cat compose/stg/deployment.yml | sed "s~IMAGE_NAME_PLACEHOLDER~${IMAGE_NAME_STG}:${IMAGE_TAG}~g" > tmp.txt && mv tmp.txt compose/stg/deployment.yml

kubectl apply -f compose/stg/deployment.yml
kubectl apply -f compose/stg/service.yml
kubectl apply -f compose/stg/ingress.yml
