#!/bin/bash
set -e

echo ${GCP_SERVICE_ACCOUNT_KEY} > /tmp/gcp-key.json
gcloud auth activate-service-account --key-file /tmp/gcp-key.json
gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
gcloud --quiet config set compute/region ${GOOGLE_COMPUTE_REGION}
gcloud --quiet config set container/cluster ${GOOGLE_CLUSTER_NAME}
gcloud --quiet container clusters get-credentials ${GOOGLE_CLUSTER_NAME}
